### ISSUE TITLE
Error with the demo example

### ISSUE THREAD

**Issue by lfnothias** [taxonomicallyinformedannotation/tima-python#10]
I am getting the following error when trying with the demo example
NB: this is the environment specified in the repo.

```
user@macos  ~/tima-python   main  python src/prepare_taxa.py                                                                                                                                   ✔  85  20:58:40
Loading paths
Loading parameters
Tool parameter OK
Top K parameter OK
Loading ...
... taxa ranks dictionary
... feature table
... metadata table
Formatting feature table ...
... WARNING: requires "Peak area" in columns (MZmine format)
... filtering top K intensities per feature
Keeping list of organisms to submit to GNVerifier
Exporting organisms for GNVerifier submission
Submitting to GNVerifier
INFO[0000] Using config file: /Users/user/Library/Application Support/gnverifier.yaml.
INFO[0000] Verified 7 records, 9 names/sec
Loading GNVerifier results
Formatting GNVerifier results
/Users/user/tima-python/src/preprocessing/taxa/clean_gnverifier.py:23: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  warning = df2[df2['count'] == 1][df2['organismCleaned'].isnull()]
/Users/user/tima-python/src/preprocessing/taxa/clean_gnverifier.py:23: FutureWarning: reindexing with a non-unique Index is deprecated and will raise in a future version.
  warning = df2[df2['count'] == 1][df2['organismCleaned'].isnull()]
Traceback (most recent call last):
  File "/Users/user/tima-python/src/prepare_taxa.py", line 105, in <module>
    dataOrganismVerified_3 = clean_gnverifier(paths, file=paths["data"]["interim"]["taxa"]["verified"])
  File "/Users/user/tima-python/src/preprocessing/taxa/clean_gnverifier.py", line 23, in clean_gnverifier
    warning = df2[df2['count'] == 1][df2['organismCleaned'].isnull()]
  File "/Users/user/opt/anaconda3/envs/tima-python/lib/python3.10/site-packages/pandas/core/frame.py", line 3497, in __getitem__
    return self._getitem_bool_array(key)
  File "/Users/user/opt/anaconda3/envs/tima-python/lib/python3.10/site-packages/pandas/core/frame.py", line 3550, in _getitem_bool_array
    key = check_bool_indexer(self.index, key)
  File "/Users/user/opt/anaconda3/envs/tima-python/lib/python3.10/site-packages/pandas/core/indexing.py", line 2372, in check_bool_indexer
    result = result.reindex(index)
  File "/Users/user/opt/anaconda3/envs/tima-python/lib/python3.10/site-packages/pandas/core/series.py", line 4669, in reindex
    return super().reindex(**kwargs)
  File "/Users/user/opt/anaconda3/envs/tima-python/lib/python3.10/site-packages/pandas/core/generic.py", line 4974, in reindex
    return self._reindex_axes(
  File "/Users/user/opt/anaconda3/envs/tima-python/lib/python3.10/site-packages/pandas/core/generic.py", line 4994, in _reindex_axes
    obj = obj._reindex_with_indexers(
  File "/Users/user/opt/anaconda3/envs/tima-python/lib/python3.10/site-packages/pandas/core/generic.py", line 5040, in _reindex_with_indexers
    new_data = new_data.reindex_indexer(
  File "/Users/user/opt/anaconda3/envs/tima-python/lib/python3.10/site-packages/pandas/core/internals/managers.py", line 679, in reindex_indexer
    self.axes[axis]._validate_can_reindex(indexer)
  File "/Users/user/opt/anaconda3/envs/tima-python/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 4107, in _validate_can_reindex
    raise ValueError("cannot reindex on an axis with duplicate labels")
ValueError: cannot reindex on an axis with duplicate labels
```

**Comment by Adafede** [comment]
Hi @lfnothias, this repo is not up-to-date as part of mandelbrot is. The most up-to-date one is https://github.com/taxonomicallyinformedannotation/tima-r. 

I adapted the README to make things more clear (https://github.com/taxonomicallyinformedannotation/tima-python/commit/35a939ea12ced84e2efb571da3cc40fc22eb7a42).

Thank you anyway for documenting the issue, any help is appreciated.
